# Generated by Django 4.0.4 on 2022-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateName', models.CharField(max_length=250, null=True)),
                ('EmailID', models.CharField(max_length=250, null=True)),
                ('ContactNumber', models.CharField(max_length=250, null=True)),
                ('Location', models.CharField(max_length=250, null=True)),
                ('KeySkills', models.CharField(max_length=250, null=True)),
                ('Experience', models.CharField(max_length=250, null=True)),
                ('designation', models.CharField(max_length=250, null=True)),
                ('Command', models.CharField(max_length=250, null=True)),
                ('college_name', models.CharField(max_length=250, null=True)),
                ('company_names', models.CharField(max_length=250, null=True)),
                ('total_exp', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
